[package]
name = "rs-wasi"
version = "0.1.0"
edition = "2021"

[build]
target = "wasm32-wasi"
rustflags = ["--cfg", "wasmedge", "--cfg", "tokio_unstable"]

[dependencies]
getrandom = "0.2.15"
rand = "0.8.5"
